### ISSUE TITLE
Logger Client DLL

### ISSUE THREAD

**Issue by CarlosX** [jglim/gunbound-server#6] opened 2020-04-30 03:21 UTC
Can you share the logger DLL ?

**Comment by jglim** [comment] 2020-04-30 04:11
Sure, the `.c` file is attached as `.txt` since comments cannot contain `.c` files. They have to be renamed and inserted into a MSVC dll project to build. I am unable to check if this works as intended since I just moved to Windows10. 

Take note that the version numbers might be off (since Softnyx's versioning can be quite messy); best to verify the addresses against the disassembly to see if they make sense.

[dllmain.c](https://github.com/jglim/gunbound-server/files/4556090/dllmain.txt)

**Comment by CarlosX** [comment] 2020-04-30 04:48
Ty.  
This client working with this DLL ?
https://github.com/jglim/gunbound-launcher/tree/master/TestClient

**Comment by jglim** [comment] 2020-04-30 05:42
Unfortunately the referenced client doesn't have any logging capability nor does it have any logging strings, so it does not work.

**Comment by CarlosX** [comment] 2020-05-01 17:39
Work, but no request to join the channel

**Comment by CarlosX** [comment] 2020-05-04 14:31
if remove gameguard, don't send the Auth(0x2000)

**Comment by jglim** [comment] 2020-05-04 14:48
Are you on a serv2-compatible client? (i.e. does it fully work with serv2?)

If it is not serv2-compatible, there are some login response changes; for a hacky workaround, you can send the 0x2001 packet to force the game state to change.

Also, if the logger is OK, can I close this issue? Please feel free to open another issue for the the channel join issue.

**Closed as completed** 2020-05-04 23:41 UTC
